//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class tOrder
    {
        public int fId { get; set; }

        [DisplayName("訂單編號")]
        public string fOrderGuid { get; set; }

        [DisplayName("會員帳號")]
        public string fUserId { get; set; }

        [DisplayName("收件人姓名")]
        [Required(ErrorMessage = "請輸入收件人姓名")]
        [MaxLength(40, ErrorMessage = "收件人姓名長度不可超過 40 個字元")]
        public string fReceiver { get; set; }

        [DisplayName("收件人信箱")]
        [Required(ErrorMessage = "請輸入收件人信箱")]
        [MaxLength(250, ErrorMessage = "收件人信箱長度無法超過250個字元")]
        [EmailAddress]
        public string fEmail { get; set; }

        [DisplayName("收件人手機")]
        [Required(ErrorMessage = "請輸入收件人手機")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",ErrorMessage = "收件人手機格式不正確")]
        public string fPhone { get; set; }

        [DisplayName("收件人地址")]
        [Required(ErrorMessage = "請輸入收件人地址")]      
        public string fAddress { get; set; }

        [DisplayName("總價")]
        public int fTotalPrice { get; set; }

        [DisplayName("訂單日期")]
        public Nullable<System.DateTime> fDate { get; set; }
    }
}
